# Generated by Django 3.0 on 2023-12-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20231204_1716'),
        ('riverApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstudentModel',
            new_name='StudentModel',
        ),
    ]
